# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Dunnkers' personal website
description: "My personal website"
keywords: "blog, data scientist, data science"
url: https://dunnkers.com
baseurl: ""

google_analytics: 
repo: http://github.com/dunnkers/dunnkers.github.io
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Jeroen Overschie
  job: Student MSc Data Science and Systems Complexity
  bio: "Web developer, Machine Learning enthusiast."
  thumb: /images/me.jpeg
  email: nandomoreira.me@gmail.com
  url: https://dunnkers.com/
  github: https://github.com/dunnkers
  linkedin: https://linkedin.com/in/jeroenoverschie/

# navbar pages
navbar:
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
