# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Jeroen Overschie
description: "Personal website of Jeroen Overschie (dunnkers)."
keywords: "blog, data scientist, data science, machine learning, artificial intelligence"
url: https://dunnkers.com
baseurl: ""

google_analytics: UA-40680192-2
repo: https://github.com/dunnkers/dunnkers.github.io
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Jeroen Overschie
  job: Student MSc Data Science and Systems Complexity
  bio: "Freelance Web developer and Machine Learning enthusiast."
  thumb: /images/author.jpeg
  email: 
  url: https://dunnkers.com/
  github: https://github.com/dunnkers
  linkedin: https://linkedin.com/in/jeroenoverschie/

# navbar pages
navbar:
  - slug: blog
    title: Blog
  - slug: projects
    title: Projects

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
